# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projet_smartviewer.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SmartViewer(object):
    def setupUi(self, SmartViewer):
        SmartViewer.setObjectName("SmartViewer")
        SmartViewer.resize(607, 547)
        self.centralwidget = QtWidgets.QWidget(SmartViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_directoryPath = QtWidgets.QLabel(self.centralwidget)
        self.lb_directoryPath.setMinimumSize(QtCore.QSize(70, 0))
        self.lb_directoryPath.setObjectName("lb_directoryPath")
        self.horizontalLayout.addWidget(self.lb_directoryPath)
        self.tb_directoryPath = QtWidgets.QLineEdit(self.centralwidget)
        self.tb_directoryPath.setObjectName("tb_directoryPath")
        self.horizontalLayout.addWidget(self.tb_directoryPath)
        self.btn_openDirectory = QtWidgets.QPushButton(self.centralwidget)
        self.btn_openDirectory.setObjectName("btn_openDirectory")
        self.horizontalLayout.addWidget(self.btn_openDirectory)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout.addWidget(self.btn_search)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.cb_subdirectory = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_subdirectory.setObjectName("cb_subdirectory")
        self.verticalLayout_3.addWidget(self.cb_subdirectory, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_search = QtWidgets.QWidget()
        self.tab_search.setObjectName("tab_search")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_search)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LayoutKeywords = QtWidgets.QHBoxLayout()
        self.LayoutKeywords.setObjectName("LayoutKeywords")
        self.lb_keywords = QtWidgets.QLabel(self.tab_search)
        self.lb_keywords.setMinimumSize(QtCore.QSize(70, 0))
        self.lb_keywords.setObjectName("lb_keywords")
        self.LayoutKeywords.addWidget(self.lb_keywords)
        self.tb_keywords = QtWidgets.QLineEdit(self.tab_search)
        self.tb_keywords.setObjectName("tb_keywords")
        self.LayoutKeywords.addWidget(self.tb_keywords)
        self.btn_apply = QtWidgets.QPushButton(self.tab_search)
        self.btn_apply.setObjectName("btn_apply")
        self.LayoutKeywords.addWidget(self.btn_apply)
        self.verticalLayout.addLayout(self.LayoutKeywords)
        self.scrollAreaImages = QtWidgets.QScrollArea(self.tab_search)
        self.scrollAreaImages.setWidgetResizable(True)
        self.scrollAreaImages.setObjectName("scrollAreaImages")
        self.scrollAreaImagesContents = QtWidgets.QWidget()
        self.scrollAreaImagesContents.setGeometry(QtCore.QRect(0, 0, 565, 314))
        self.scrollAreaImagesContents.setObjectName("scrollAreaImagesContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaImagesContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayoutImages = QtWidgets.QGridLayout()
        self.gridLayoutImages.setObjectName("gridLayoutImages")
        self.gridLayout.addLayout(self.gridLayoutImages, 0, 0, 1, 1)
        self.scrollAreaImages.setWidget(self.scrollAreaImagesContents)
        self.verticalLayout.addWidget(self.scrollAreaImages)
        self.tabWidget.addTab(self.tab_search, "")
        self.tab_others = QtWidgets.QWidget()
        self.tab_others.setObjectName("tab_others")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_others)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_others)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 565, 347))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_others, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.lb_nbImages = QtWidgets.QLabel(self.centralwidget)
        self.lb_nbImages.setObjectName("lb_nbImages")
        self.verticalLayout_2.addWidget(self.lb_nbImages, 0, QtCore.Qt.AlignRight)
        SmartViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SmartViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 607, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        SmartViewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SmartViewer)
        self.statusbar.setObjectName("statusbar")
        SmartViewer.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(SmartViewer)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(SmartViewer)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SmartViewer)

    def retranslateUi(self, SmartViewer):
        _translate = QtCore.QCoreApplication.translate
        SmartViewer.setWindowTitle(_translate("SmartViewer", "Smart Viewer"))
        self.lb_directoryPath.setText(_translate("SmartViewer", "Directory Path"))
        self.btn_openDirectory.setText(_translate("SmartViewer", "Open Directory Dialog"))
        self.btn_search.setText(_translate("SmartViewer", "Search"))
        self.cb_subdirectory.setText(_translate("SmartViewer", "Subdirectory"))
        self.lb_keywords.setText(_translate("SmartViewer", "Keywords"))
        self.btn_apply.setText(_translate("SmartViewer", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search), _translate("SmartViewer", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_others), _translate("SmartViewer", "Others"))
        self.lb_nbImages.setText(_translate("SmartViewer", "0 Images"))
        self.menuFile.setTitle(_translate("SmartViewer", "File"))
        self.actionQuit.setText(_translate("SmartViewer", "Quit"))

